print('Primeiro código em Python')
Num1 = int(input('Digite um número:'))
Num2 = int(input('Digite outro número:'))
print('Calculando... ',Num1, '+',Num2,'...')
print('Resultado é:', Num1+Num2)
print('Finalizando o primeiro código em Python')
